sudo: true
services:
    - docker

before_install:
    - docker info
    - docker version

    - docker build  -t behave  .

script:
    - echo "==> Validating the test results..."
    - cd test  &&  ./run-test.sh | grep '1 feature passed, 0 failed, 0 skipped'
